export const TableHeaders = [
  "Index",
  "Column1",
  "Column2",
  "Column3",
  "Column4",
  "Column5",
  "Column6",
  "Column7",
  "Column8",
  "Column9",
  "Column10",
  "Column11",
  "Column12",
  "Column13",
  "Column14",
  "Column15",
];

export const DemoRowValues = [
  {
    Index: 1,
    Column1: "sadasdasdfd",
    Column2: "sadasdasdfd",
    Column3: "sadasdasdfd",
    Column4: "sadasdasdfd",
    Column5: "sadasdasdfd",
    Column6: "sadasdasdfd",
    Column7: "sadasdasdfd",
    Column8: "sadasdasdfd",
    Column9: "sadasdasdfd",
    Column10: "sadasdasdfd",
    Column11: "sadasdasdfd",
    Column12: "sadasdasdfd",
    Column13: "sadasdasdfd",
    Column14: "sadasdasdfd",
    Column15: "sadasdasdfd",
  },
  {
    Index: 2,
    Column1: "sadasdasdfd",
    Column2: "sadasdasdfd",
    Column3: "sadasdasdfd",
    Column4: "sadasdasdfd",
    Column5: "sadasdasdfd",
    Column6: "sadasdasdfd",
    Column7: "sadasdasdfd",
    Column8: "sadasdasdfd",
    Column9: "sadasdasdfd",
    Column10: "sadasdasdfd",
    Column11: "sadasdasdfd",
    Column12: "sadasdasdfd",
    Column13: "sadasdasdfd",
    Column14: "sadasdasdfd",
    Column15: "sadasdasdfd",
  },
  {
    Index: 3,
    Column1: "sadasdasdfd",
    Column2: "sadasdasdfd",
    Column3: "sadasdasdfd",
    Column4: "sadasdasdfd",
    Column5: "sadasdasdfd",
    Column6: "sadasdasdfd",
    Column7: "sadasdasdfd",
    Column8: "sadasdasdfd",
    Column9: "sadasdasdfd",
    Column10: "sadasdasdfd",
    Column11: "sadasdasdfd",
    Column12: "sadasdasdfd",
    Column13: "sadasdasdfd",
    Column14: "sadasdasdfd",
    Column15: "sadasdasdfd",
  },
  {
    Index: 4,
    Column1: "sadasdasdfd",
    Column2: "sadasdasdfd",
    Column3: "sadasdasdfd",
    Column4: "sadasdasdfd",
    Column5: "sadasdasdfd",
    Column6: "sadasdasdfd",
    Column7: "sadasdasdfd",
    Column8: "sadasdasdfd",
    Column9: "sadasdasdfd",
    Column10: "sadasdasdfd",
    Column11: "sadasdasdfd",
    Column12: "sadasdasdfd",
    Column13: "sadasdasdfd",
    Column14: "sadasdasdfd",
    Column15: "sadasdasdfd",
  },
  {
    Index: 5,
    Column1: "sadasdasdfd",
    Column2: "sadasdasdfd",
    Column3: "sadasdasdfd",
    Column4: "sadasdasdfd",
    Column5: "sadasdasdfd",
    Column6: "sadasdasdfd",
    Column7: "sadasdasdfd",
    Column8: "sadasdasdfd",
    Column9: "sadasdasdfd",
    Column10: "sadasdasdfd",
    Column11: "sadasdasdfd",
    Column12: "sadasdasdfd",
    Column13: "sadasdasdfd",
    Column14: "sadasdasdfd",
    Column15: "sadasdasdfd",
  },
  {
    Index: 6,
    Column1: "sadasdasdfd",
    Column2: "sadasdasdfd",
    Column3: "sadasdasdfd",
    Column4: "sadasdasdfd",
    Column5: "sadasdasdfd",
    Column6: "sadasdasdfd",
    Column7: "sadasdasdfd",
    Column8: "sadasdasdfd",
    Column9: "sadasdasdfd",
    Column10: "sadasdasdfd",
    Column11: "sadasdasdfd",
    Column12: "sadasdasdfd",
    Column13: "sadasdasdfd",
    Column14: "sadasdasdfd",
    Column15: "sadasdasdfd",
  },
  {
    Index: 7,
    Column1: "sadasdasdfd",
    Column2: "sadasdasdfd",
    Column3: "sadasdasdfd",
    Column4: "sadasdasdfd",
    Column5: "sadasdasdfd",
    Column6: "sadasdasdfd",
    Column7: "sadasdasdfd",
    Column8: "sadasdasdfd",
    Column9: "sadasdasdfd",
    Column10: "sadasdasdfd",
    Column11: "sadasdasdfd",
    Column12: "sadasdasdfd",
    Column13: "sadasdasdfd",
    Column14: "sadasdasdfd",
    Column15: "sadasdasdfd",
  },
  {
    Index: 8,
    Column1: "sadasdasdfd",
    Column2: "sadasdasdfd",
    Column3: "sadasdasdfd",
    Column4: "sadasdasdfd",
    Column5: "sadasdasdfd",
    Column6: "sadasdasdfd",
    Column7: "sadasdasdfd",
    Column8: "sadasdasdfd",
    Column9: "sadasdasdfd",
    Column10: "sadasdasdfd",
    Column11: "sadasdasdfd",
    Column12: "sadasdasdfd",
    Column13: "sadasdasdfd",
    Column14: "sadasdasdfd",
    Column15: "sadasdasdfd",
  },
  {
    Index: 7,
    Column1: "sadasdasdfd",
    Column2: "sadasdasdfd",
    Column3: "sadasdasdfd",
    Column4: "sadasdasdfd",
    Column5: "sadasdasdfd",
    Column6: "sadasdasdfd",
    Column7: "sadasdasdfd",
    Column8: "sadasdasdfd",
    Column9: "sadasdasdfd",
    Column10: "sadasdasdfd",
    Column11: "sadasdasdfd",
    Column12: "sadasdasdfd",
    Column13: "sadasdasdfd",
    Column14: "sadasdasdfd",
    Column15: "sadasdasdfd",
  },
];

export const navLinks = [
  { href: "#home", label: "Home" },
  { href: "#about-us", label: "Page 1" },
  { href: "#products", label: "Page 2" },
  { href: "#contact-us", label: "Page 3" },
];

export const navigation = [
  {
    name: "Filter",
    href: "#",
    current: true,
    icon: "/public/icons/Funnel.svg",
  },
  {
    name: "Dashboard",
    href: "#",
    current: false,
    icon: "/public/icons/ArrowDownCircle.svg",
  },
  {
    name: "Data Upload",
    href: "#",
    current: false,
    icon: "/public/icons/CloudArrowUp.svg",
  },
  {
    name: "Entity Tracking",
    href: "#",
    current: false,
    icon: "/public/icons/PaperClip.svg",
  },
  {
    name: "Report Generation",
    href: "#",
    current: false,
    icon: "/public/icons/ClipboardDocumentList.svg",
  },
  {
    name: "About",
    href: "#",
    current: false,
    icon: "/public/icons/AtSymbol.svg",
  },
];

export function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}
