export const TableHeaders = [
  "Index",
  "Column2",
  "Column1",
  "Column3",
  "Column4",
  "Column5",
  "Column6",
  "Column7",
  "Column8",
  "Column9",
  "Column10",
];

export const DemoRowValues = [
  {
    Index: 1,
    Column2: "sadasdasdfd",
    Column1: "sadasdasdfd",
    Column3: "sadasdasdfd",
    Column4: "sadasdasdfd",
    Column5: "sadasdasdfd",
    Column6: "sadasdasdfd",
    Column7: "sadasdasdfd",
    Column8: "sadasdasdfd",
    Column9: "sadasdasdfd",
    Column10: "sadasdasdfd",
  },
  {
    Index: 2,
    Column2: "sadasdasdfd",
    Column1: "sadasdasdfd",
    Column3: "sadasdasdfd",
    Column4: "sadasdasdfd",
    Column5: "sadasdasdfd",
    Column6: "sadasdasdfd",
    Column7: "sadasdasdfd",
    Column8: "sadasdasdfd",
    Column9: "sadasdasdfd",
    Column10: "sadasdasdfd",
  },
];
